[package]
name = "edbot"
version = "0.0.1"
edition = "2021"

[dependencies]
serenity = { version = "0.10.10", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
